# Generated by Django 4.0 on 2021-12-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_article',
            field=models.BooleanField(default=True),
        ),
    ]
